#!/bin/bash
LOG_PATH="/home/n/document/code/profiles/raw/custom_hooks.log"
xml=$(virsh dumpxml $1)
TITLE=$(echo $xml | xmllint --xpath 'string(/domain/title)' -)

if [[ $TITLE == *"-allgpu"* ]]; then
  case $2 in
    "prepare")
      echo "$*" | tee -a $LOG_PATH
      # systemctl start libvirt-nosleep@"$1"  2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      # ./allGPU2guest.sh launch 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ;;

    "release")
      echo "$*" | tee -a $LOG_PATH
      # systemctl stop libvirt-nosleep@"$1"  2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      # ./allGPU2host.sh launch 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ;;
  esac
elif [[ $TITLE == *"-nvidia"* ]]; then
  case $2 in
    "prepare")
      echo "$*" | tee -a $LOG_PATH
      ./nvidia2guest.sh launch 2>&1 | tee -a $LOG_PATH
      ;;

    "release")
      echo "$*" | tee -a $LOG_PATH
      ./nvidia2host.sh launch 2>&1 | tee -a $LOG_PATH
      ;;
  esac
fi