#!/bin/bash

OBJECT="$1"
OPERATION="$2"

if [[ $OBJECT == *"-allgpu"* ]]; then
  case "$OPERATION" in
    "prepare")
      systemctl start libvirt-nosleep@"$OBJECT"  2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ./allGPU2guest.sh launch 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ;;

    "release")
      systemctl stop libvirt-nosleep@"$OBJECT"  2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ./allGPU2host.sh launch 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ;;
  esac
elif [[ $OBJECT == *"-nvidia"* ]]; then
  case "$OPERATION" in
    "prepare")
      ./nvidia2guest.sh launch 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ;;

    "release")
      ./nvidia2host.sh launch 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
      ;;
  esac
fi